// CODE GENERATED USING MAKOTEMPLATES.ORG, DO NOT EDIT.
#define CAN_VERSION "0.1.2"

#include <stdint.h>

// GENERIC - Modulo generico para facilitar implementacoes genericas
#define CAN_SIGNATURE_GENERIC 0
// GENERIC - STATE - Module state report
#define CAN_MSG_GENERIC_STATE_ID 50
#define CAN_MSG_GENERIC_STATE_LENGTH 3
#define CAN_MSG_GENERIC_STATE_FREQUENCY 0
#define CAN_MSG_GENERIC_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_GENERIC_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_GENERIC_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_GENERIC_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_GENERIC_STATE_STATE_TYPE uint8_t
#define CAN_MSG_GENERIC_STATE_STATE_UNITS ""
#define CAN_MSG_GENERIC_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_GENERIC_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_GENERIC_STATE_ERROR_UNITS ""
// GENERIC - GENERIC - Generic topic
#define CAN_MSG_GENERIC_GENERIC_ID 51
#define CAN_MSG_GENERIC_GENERIC_LENGTH 1
#define CAN_MSG_GENERIC_GENERIC_FREQUENCY 0
#define CAN_MSG_GENERIC_GENERIC_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_GENERIC_GENERIC_SIGNATURE_TYPE uint8_t
#define CAN_MSG_GENERIC_GENERIC_SIGNATURE_UNITS ""


// MIC19 - Modulo de Interface de Controle
#define CAN_SIGNATURE_MIC19 240
// MIC19 - STATE - Module state report
#define CAN_MSG_MIC19_STATE_ID 30
#define CAN_MSG_MIC19_STATE_LENGTH 3
#define CAN_MSG_MIC19_STATE_FREQUENCY 5
#define CAN_MSG_MIC19_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MIC19_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MIC19_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MIC19_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MIC19_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MIC19_STATE_STATE_UNITS ""
#define CAN_MSG_MIC19_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MIC19_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MIC19_STATE_ERROR_UNITS ""
// MIC19 - MOTOR - Motor controller parameters
#define CAN_MSG_MIC19_MOTOR_ID 31
#define CAN_MSG_MIC19_MOTOR_LENGTH 4
#define CAN_MSG_MIC19_MOTOR_FREQUENCY 50
#define CAN_MSG_MIC19_MOTOR_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MIC19_MOTOR_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MIC19_MOTOR_SIGNATURE_UNITS ""
#define CAN_MSG_MIC19_MOTOR_MOTOR_BYTE 1 //<!" Motor state
#define CAN_MSG_MIC19_MOTOR_MOTOR_TYPE uint8_t
#define CAN_MSG_MIC19_MOTOR_MOTOR_UNITS ""
#define CAN_MSG_MIC19_MOTOR_MOTOR_MOTOR_ON_BIT 0
#define CAN_MSG_MIC19_MOTOR_MOTOR_DMS_ON_BIT 1
#define CAN_MSG_MIC19_MOTOR_MOTOR_REVERSE_BIT 2
#define CAN_MSG_MIC19_MOTOR_D_BYTE 2 //<!" Motor Duty Cycle
#define CAN_MSG_MIC19_MOTOR_D_TYPE uint8_t
#define CAN_MSG_MIC19_MOTOR_D_UNITS "%"
#define CAN_MSG_MIC19_MOTOR_I_BYTE 3 //<!" Motor Soft Start
#define CAN_MSG_MIC19_MOTOR_I_TYPE uint8_t
#define CAN_MSG_MIC19_MOTOR_I_UNITS "%"
// MIC19 - PUMPS - Pumps controller parameters
#define CAN_MSG_MIC19_PUMPS_ID 41
#define CAN_MSG_MIC19_PUMPS_LENGTH 2
#define CAN_MSG_MIC19_PUMPS_FREQUENCY 4
#define CAN_MSG_MIC19_PUMPS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MIC19_PUMPS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MIC19_PUMPS_SIGNATURE_UNITS ""
#define CAN_MSG_MIC19_PUMPS_PUMPS_BYTE 1 //<!" Pumps state
#define CAN_MSG_MIC19_PUMPS_PUMPS_TYPE uint8_t
#define CAN_MSG_MIC19_PUMPS_PUMPS_UNITS ""
#define CAN_MSG_MIC19_PUMPS_PUMPS_PUMP1_BIT 0
#define CAN_MSG_MIC19_PUMPS_PUMPS_PUMP2_BIT 1
#define CAN_MSG_MIC19_PUMPS_PUMPS_PUMP3_BIT 2
// MIC19 - MPPTS - Mppts controller parameters
#define CAN_MSG_MIC19_MPPTS_ID 200
#define CAN_MSG_MIC19_MPPTS_LENGTH 3
#define CAN_MSG_MIC19_MPPTS_FREQUENCY 4
#define CAN_MSG_MIC19_MPPTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MIC19_MPPTS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MIC19_MPPTS_SIGNATURE_UNITS ""
#define CAN_MSG_MIC19_MPPTS_MPPTS_ON_BYTE 1 //<!" MPPTs state
#define CAN_MSG_MIC19_MPPTS_MPPTS_ON_TYPE uint8_t
#define CAN_MSG_MIC19_MPPTS_MPPTS_ON_UNITS ""
#define CAN_MSG_MIC19_MPPTS_MPPTS_ON_MPPTS_ON_BIT 0
#define CAN_MSG_MIC19_MPPTS_POT_BYTE 2 //<!" MPPTs maximum power limitation
#define CAN_MSG_MIC19_MPPTS_POT_TYPE uint8_t
#define CAN_MSG_MIC19_MPPTS_POT_UNITS "%"
// MIC19 - MCS - MCS controller parameters
#define CAN_MSG_MIC19_MCS_ID 32
#define CAN_MSG_MIC19_MCS_LENGTH 2
#define CAN_MSG_MIC19_MCS_FREQUENCY 50
#define CAN_MSG_MIC19_MCS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MIC19_MCS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MIC19_MCS_SIGNATURE_UNITS ""
#define CAN_MSG_MIC19_MCS_BOAT_ON_BYTE 1 //<!" Boat state
#define CAN_MSG_MIC19_MCS_BOAT_ON_TYPE uint8_t
#define CAN_MSG_MIC19_MCS_BOAT_ON_UNITS ""
#define CAN_MSG_MIC19_MCS_BOAT_ON_BOAT_ON_BIT 0
// MIC19 - MDE - Steereing wheel controls
#define CAN_MSG_MIC19_MDE_ID 33
#define CAN_MSG_MIC19_MDE_LENGTH 3
#define CAN_MSG_MIC19_MDE_FREQUENCY 50
#define CAN_MSG_MIC19_MDE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MIC19_MDE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MIC19_MDE_SIGNATURE_UNITS ""
#define CAN_MSG_MIC19_MDE_POSITION_L_BYTE 1 //<!" Steering wheel position, byte LOW
#define CAN_MSG_MIC19_MDE_POSITION_L_TYPE uint16_t
#define CAN_MSG_MIC19_MDE_POSITION_L_UNITS "°/100"
#define CAN_MSG_MIC19_MDE_POSITION_H_BYTE 2 //<!" Steering wheel position, byte HIGH
#define CAN_MSG_MIC19_MDE_POSITION_H_TYPE uint16_t
#define CAN_MSG_MIC19_MDE_POSITION_H_UNITS "°/100"


// MDE22 - Modulo da Direção Elétrica
#define CAN_SIGNATURE_MDE22 170
// MDE22 - STATE - Module state report
#define CAN_MSG_MDE22_STATE_ID 100
#define CAN_MSG_MDE22_STATE_LENGTH 3
#define CAN_MSG_MDE22_STATE_FREQUENCY 1
#define CAN_MSG_MDE22_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MDE22_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MDE22_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MDE22_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MDE22_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MDE22_STATE_STATE_UNITS ""
#define CAN_MSG_MDE22_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MDE22_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MDE22_STATE_ERROR_UNITS ""
// MDE22 - STEERINGBAT_MEASUREMENTS - Auxiliar Battery Voltage
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_ID 201
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_LENGTH 7
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_FREQUENCY 10
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_SIGNATURE_UNITS ""
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATVOLTAGE_L_BYTE 1 //<!" Battery Voltage, byte low
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATVOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATVOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATVOLTAGE_H_BYTE 2 //<!" Battery Voltage, byte high
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATVOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATVOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_POSITION_L_BYTE 3 //<!" Tail Poisition, byte low
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_POSITION_L_TYPE uint16_t
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_POSITION_L_UNITS "°/100"
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_POSITION_H_BYTE 4 //<!" Tail Poisition, byte high
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_POSITION_H_TYPE uint16_t
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_POSITION_H_UNITS "°/100"
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATCURRENT_L_BYTE 5 //<!" Battery Current, byte low
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATCURRENT_L_TYPE uint16_t
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATCURRENT_L_UNITS "A/100"
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATCURRENT_H_BYTE 6 //<!" Battery Current, byte high
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATCURRENT_H_TYPE uint16_t
#define CAN_MSG_MDE22_STEERINGBAT_MEASUREMENTS_BATCURRENT_H_UNITS "A/100"


// MVC19_1 - Modulo de voltimetro 1
#define CAN_SIGNATURE_MVC19_1 210
// MVC19_1 - STATE - Module state report
#define CAN_MSG_MVC19_1_STATE_ID 101
#define CAN_MSG_MVC19_1_STATE_LENGTH 3
#define CAN_MSG_MVC19_1_STATE_FREQUENCY 1
#define CAN_MSG_MVC19_1_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MVC19_1_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MVC19_1_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MVC19_1_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MVC19_1_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MVC19_1_STATE_STATE_UNITS ""
#define CAN_MSG_MVC19_1_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MVC19_1_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MVC19_1_STATE_ERROR_UNITS ""


// MVC19_2 - Modulo de voltimetro 2
#define CAN_SIGNATURE_MVC19_2 211
// MVC19_2 - STATE - Module state report
#define CAN_MSG_MVC19_2_STATE_ID 102
#define CAN_MSG_MVC19_2_STATE_LENGTH 3
#define CAN_MSG_MVC19_2_STATE_FREQUENCY 1
#define CAN_MSG_MVC19_2_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MVC19_2_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MVC19_2_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MVC19_2_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MVC19_2_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MVC19_2_STATE_STATE_UNITS ""
#define CAN_MSG_MVC19_2_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MVC19_2_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MVC19_2_STATE_ERROR_UNITS ""


// MCC19_1 - Modulo controlador de carga
#define CAN_SIGNATURE_MCC19_1 225
// MCC19_1 - STATE - Module state report
#define CAN_MSG_MCC19_1_STATE_ID 103
#define CAN_MSG_MCC19_1_STATE_LENGTH 3
#define CAN_MSG_MCC19_1_STATE_FREQUENCY 1
#define CAN_MSG_MCC19_1_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_1_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_1_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_1_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MCC19_1_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MCC19_1_STATE_STATE_UNITS ""
#define CAN_MSG_MCC19_1_STATE_CONTROL_BYTE 2 //<!" Control flags for operating point
#define CAN_MSG_MCC19_1_STATE_CONTROL_TYPE uint8_t
#define CAN_MSG_MCC19_1_STATE_CONTROL_UNITS ""
#define CAN_MSG_MCC19_1_STATE_CONTROL_ENABLE_BIT 0
#define CAN_MSG_MCC19_1_STATE_CONTROL_VI_SAFE_RANGE_BIT 1
#define CAN_MSG_MCC19_1_STATE_CONTROL_VO_SAFE_RANGE_BIT 2
#define CAN_MSG_MCC19_1_STATE_CONTROL_VI_STABLE_BIT 3
#define CAN_MSG_MCC19_1_STATE_CONTROL_DT_SAFE_RANGE_BIT 4
// MCC19_1 - MEASUREMENTS - All measurements from the converter
#define CAN_MSG_MCC19_1_MEASUREMENTS_ID 202
#define CAN_MSG_MCC19_1_MEASUREMENTS_LENGTH 8
#define CAN_MSG_MCC19_1_MEASUREMENTS_FREQUENCY 30
#define CAN_MSG_MCC19_1_MEASUREMENTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_1_MEASUREMENTS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_1_MEASUREMENTS_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_1_MEASUREMENTS_OUTPUT_VOLTAGE_L_BYTE 1 //<!" Average output voltage, byte low
#define CAN_MSG_MCC19_1_MEASUREMENTS_OUTPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_1_MEASUREMENTS_OUTPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_1_MEASUREMENTS_OUTPUT_VOLTAGE_H_BYTE 2 //<!" Average output voltage, byte high
#define CAN_MSG_MCC19_1_MEASUREMENTS_OUTPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_1_MEASUREMENTS_OUTPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_CURRENT_L_BYTE 3 //<!" Average input current, byte low
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_CURRENT_L_TYPE uint16_t
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_CURRENT_L_UNITS "A/100"
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_CURRENT_H_BYTE 4 //<!" Average input current, byte high
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_CURRENT_H_TYPE uint16_t
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_CURRENT_H_UNITS "A/100"
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_VOLTAGE_L_BYTE 5 //<!" Average input voltage, byte low
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_VOLTAGE_H_BYTE 6 //<!" Average input voltage, byte high
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_1_MEASUREMENTS_INPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_1_MEASUREMENTS_DT_BYTE 7 //<!" converter's duty cycle
#define CAN_MSG_MCC19_1_MEASUREMENTS_DT_TYPE uint8_t
#define CAN_MSG_MCC19_1_MEASUREMENTS_DT_UNITS "%/255"


// MCC19_2 - Modulo controlador de carga
#define CAN_SIGNATURE_MCC19_2 226
// MCC19_2 - STATE - Module state report
#define CAN_MSG_MCC19_2_STATE_ID 104
#define CAN_MSG_MCC19_2_STATE_LENGTH 3
#define CAN_MSG_MCC19_2_STATE_FREQUENCY 1
#define CAN_MSG_MCC19_2_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_2_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_2_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_2_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MCC19_2_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MCC19_2_STATE_STATE_UNITS ""
#define CAN_MSG_MCC19_2_STATE_CONTROL_BYTE 2 //<!" Control flags for operating point
#define CAN_MSG_MCC19_2_STATE_CONTROL_TYPE uint8_t
#define CAN_MSG_MCC19_2_STATE_CONTROL_UNITS ""
#define CAN_MSG_MCC19_2_STATE_CONTROL_ENABLE_BIT 0
#define CAN_MSG_MCC19_2_STATE_CONTROL_VI_SAFE_RANGE_BIT 1
#define CAN_MSG_MCC19_2_STATE_CONTROL_VO_SAFE_RANGE_BIT 2
#define CAN_MSG_MCC19_2_STATE_CONTROL_VI_STABLE_BIT 3
#define CAN_MSG_MCC19_2_STATE_CONTROL_DT_SAFE_RANGE_BIT 4
// MCC19_2 - MEASUREMENTS - All measurements from the converter
#define CAN_MSG_MCC19_2_MEASUREMENTS_ID 203
#define CAN_MSG_MCC19_2_MEASUREMENTS_LENGTH 8
#define CAN_MSG_MCC19_2_MEASUREMENTS_FREQUENCY 30
#define CAN_MSG_MCC19_2_MEASUREMENTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_2_MEASUREMENTS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_2_MEASUREMENTS_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_2_MEASUREMENTS_OUTPUT_VOLTAGE_L_BYTE 1 //<!" Average output voltage, byte low
#define CAN_MSG_MCC19_2_MEASUREMENTS_OUTPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_2_MEASUREMENTS_OUTPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_2_MEASUREMENTS_OUTPUT_VOLTAGE_H_BYTE 2 //<!" Average output voltage, byte high
#define CAN_MSG_MCC19_2_MEASUREMENTS_OUTPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_2_MEASUREMENTS_OUTPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_CURRENT_L_BYTE 3 //<!" Average input current, byte low
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_CURRENT_L_TYPE uint16_t
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_CURRENT_L_UNITS "A/100"
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_CURRENT_H_BYTE 4 //<!" Average input current, byte high
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_CURRENT_H_TYPE uint16_t
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_CURRENT_H_UNITS "A/100"
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_VOLTAGE_L_BYTE 5 //<!" Average input voltage, byte low
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_VOLTAGE_H_BYTE 6 //<!" Average input voltage, byte high
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_2_MEASUREMENTS_INPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_2_MEASUREMENTS_DT_BYTE 7 //<!" converter's duty cycle
#define CAN_MSG_MCC19_2_MEASUREMENTS_DT_TYPE uint8_t
#define CAN_MSG_MCC19_2_MEASUREMENTS_DT_UNITS "%/255"


// MCC19_3 - Modulo controlador de carga
#define CAN_SIGNATURE_MCC19_3 227
// MCC19_3 - STATE - Module state report
#define CAN_MSG_MCC19_3_STATE_ID 105
#define CAN_MSG_MCC19_3_STATE_LENGTH 3
#define CAN_MSG_MCC19_3_STATE_FREQUENCY 1
#define CAN_MSG_MCC19_3_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_3_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_3_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_3_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MCC19_3_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MCC19_3_STATE_STATE_UNITS ""
#define CAN_MSG_MCC19_3_STATE_CONTROL_BYTE 2 //<!" Control flags for operating point
#define CAN_MSG_MCC19_3_STATE_CONTROL_TYPE uint8_t
#define CAN_MSG_MCC19_3_STATE_CONTROL_UNITS ""
#define CAN_MSG_MCC19_3_STATE_CONTROL_ENABLE_BIT 0
#define CAN_MSG_MCC19_3_STATE_CONTROL_VI_SAFE_RANGE_BIT 1
#define CAN_MSG_MCC19_3_STATE_CONTROL_VO_SAFE_RANGE_BIT 2
#define CAN_MSG_MCC19_3_STATE_CONTROL_VI_STABLE_BIT 3
#define CAN_MSG_MCC19_3_STATE_CONTROL_DT_SAFE_RANGE_BIT 4
// MCC19_3 - MEASUREMENTS - All measurements from the converter
#define CAN_MSG_MCC19_3_MEASUREMENTS_ID 204
#define CAN_MSG_MCC19_3_MEASUREMENTS_LENGTH 8
#define CAN_MSG_MCC19_3_MEASUREMENTS_FREQUENCY 30
#define CAN_MSG_MCC19_3_MEASUREMENTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_3_MEASUREMENTS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_3_MEASUREMENTS_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_3_MEASUREMENTS_OUTPUT_VOLTAGE_L_BYTE 1 //<!" Average output voltage, byte low
#define CAN_MSG_MCC19_3_MEASUREMENTS_OUTPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_3_MEASUREMENTS_OUTPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_3_MEASUREMENTS_OUTPUT_VOLTAGE_H_BYTE 2 //<!" Average output voltage, byte high
#define CAN_MSG_MCC19_3_MEASUREMENTS_OUTPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_3_MEASUREMENTS_OUTPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_CURRENT_L_BYTE 3 //<!" Average input current, byte low
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_CURRENT_L_TYPE uint16_t
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_CURRENT_L_UNITS "A/100"
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_CURRENT_H_BYTE 4 //<!" Average input current, byte high
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_CURRENT_H_TYPE uint16_t
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_CURRENT_H_UNITS "A/100"
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_VOLTAGE_L_BYTE 5 //<!" Average input voltage, byte low
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_VOLTAGE_H_BYTE 6 //<!" Average input voltage, byte high
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_3_MEASUREMENTS_INPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_3_MEASUREMENTS_DT_BYTE 7 //<!" converter's duty cycle
#define CAN_MSG_MCC19_3_MEASUREMENTS_DT_TYPE uint8_t
#define CAN_MSG_MCC19_3_MEASUREMENTS_DT_UNITS "%/255"


// MCC19_4 - Modulo controlador de carga
#define CAN_SIGNATURE_MCC19_4 228
// MCC19_4 - STATE - Module state report
#define CAN_MSG_MCC19_4_STATE_ID 106
#define CAN_MSG_MCC19_4_STATE_LENGTH 3
#define CAN_MSG_MCC19_4_STATE_FREQUENCY 1
#define CAN_MSG_MCC19_4_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_4_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_4_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_4_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MCC19_4_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MCC19_4_STATE_STATE_UNITS ""
#define CAN_MSG_MCC19_4_STATE_CONTROL_BYTE 2 //<!" Control flags for operating point
#define CAN_MSG_MCC19_4_STATE_CONTROL_TYPE uint8_t
#define CAN_MSG_MCC19_4_STATE_CONTROL_UNITS ""
#define CAN_MSG_MCC19_4_STATE_CONTROL_ENABLE_BIT 0
#define CAN_MSG_MCC19_4_STATE_CONTROL_VI_SAFE_RANGE_BIT 1
#define CAN_MSG_MCC19_4_STATE_CONTROL_VO_SAFE_RANGE_BIT 2
#define CAN_MSG_MCC19_4_STATE_CONTROL_VI_STABLE_BIT 3
#define CAN_MSG_MCC19_4_STATE_CONTROL_DT_SAFE_RANGE_BIT 4
// MCC19_4 - MEASUREMENTS - All measurements from the converter
#define CAN_MSG_MCC19_4_MEASUREMENTS_ID 205
#define CAN_MSG_MCC19_4_MEASUREMENTS_LENGTH 8
#define CAN_MSG_MCC19_4_MEASUREMENTS_FREQUENCY 30
#define CAN_MSG_MCC19_4_MEASUREMENTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_4_MEASUREMENTS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_4_MEASUREMENTS_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_4_MEASUREMENTS_OUTPUT_VOLTAGE_L_BYTE 1 //<!" Average output voltage, byte low
#define CAN_MSG_MCC19_4_MEASUREMENTS_OUTPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_4_MEASUREMENTS_OUTPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_4_MEASUREMENTS_OUTPUT_VOLTAGE_H_BYTE 2 //<!" Average output voltage, byte high
#define CAN_MSG_MCC19_4_MEASUREMENTS_OUTPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_4_MEASUREMENTS_OUTPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_CURRENT_L_BYTE 3 //<!" Average input current, byte low
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_CURRENT_L_TYPE uint16_t
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_CURRENT_L_UNITS "A/100"
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_CURRENT_H_BYTE 4 //<!" Average input current, byte high
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_CURRENT_H_TYPE uint16_t
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_CURRENT_H_UNITS "A/100"
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_VOLTAGE_L_BYTE 5 //<!" Average input voltage, byte low
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_VOLTAGE_H_BYTE 6 //<!" Average input voltage, byte high
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_4_MEASUREMENTS_INPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_4_MEASUREMENTS_DT_BYTE 7 //<!" converter's duty cycle
#define CAN_MSG_MCC19_4_MEASUREMENTS_DT_TYPE uint8_t
#define CAN_MSG_MCC19_4_MEASUREMENTS_DT_UNITS "%/255"


// MCC19_5 - Modulo controlador de carga
#define CAN_SIGNATURE_MCC19_5 229
// MCC19_5 - STATE - Module state report
#define CAN_MSG_MCC19_5_STATE_ID 107
#define CAN_MSG_MCC19_5_STATE_LENGTH 3
#define CAN_MSG_MCC19_5_STATE_FREQUENCY 1
#define CAN_MSG_MCC19_5_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_5_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_5_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_5_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MCC19_5_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MCC19_5_STATE_STATE_UNITS ""
#define CAN_MSG_MCC19_5_STATE_CONTROL_BYTE 2 //<!" Control flags for operating point
#define CAN_MSG_MCC19_5_STATE_CONTROL_TYPE uint8_t
#define CAN_MSG_MCC19_5_STATE_CONTROL_UNITS ""
#define CAN_MSG_MCC19_5_STATE_CONTROL_ENABLE_BIT 0
#define CAN_MSG_MCC19_5_STATE_CONTROL_VI_SAFE_RANGE_BIT 1
#define CAN_MSG_MCC19_5_STATE_CONTROL_VO_SAFE_RANGE_BIT 2
#define CAN_MSG_MCC19_5_STATE_CONTROL_VI_STABLE_BIT 3
#define CAN_MSG_MCC19_5_STATE_CONTROL_DT_SAFE_RANGE_BIT 4
// MCC19_5 - MEASUREMENTS - All measurements from the converter
#define CAN_MSG_MCC19_5_MEASUREMENTS_ID 206
#define CAN_MSG_MCC19_5_MEASUREMENTS_LENGTH 8
#define CAN_MSG_MCC19_5_MEASUREMENTS_FREQUENCY 30
#define CAN_MSG_MCC19_5_MEASUREMENTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_5_MEASUREMENTS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_5_MEASUREMENTS_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_5_MEASUREMENTS_OUTPUT_VOLTAGE_L_BYTE 1 //<!" Average output voltage, byte low
#define CAN_MSG_MCC19_5_MEASUREMENTS_OUTPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_5_MEASUREMENTS_OUTPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_5_MEASUREMENTS_OUTPUT_VOLTAGE_H_BYTE 2 //<!" Average output voltage, byte high
#define CAN_MSG_MCC19_5_MEASUREMENTS_OUTPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_5_MEASUREMENTS_OUTPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_CURRENT_L_BYTE 3 //<!" Average input current, byte low
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_CURRENT_L_TYPE uint16_t
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_CURRENT_L_UNITS "A/100"
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_CURRENT_H_BYTE 4 //<!" Average input current, byte high
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_CURRENT_H_TYPE uint16_t
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_CURRENT_H_UNITS "A/100"
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_VOLTAGE_L_BYTE 5 //<!" Average input voltage, byte low
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_VOLTAGE_H_BYTE 6 //<!" Average input voltage, byte high
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_5_MEASUREMENTS_INPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_5_MEASUREMENTS_DT_BYTE 7 //<!" converter's duty cycle
#define CAN_MSG_MCC19_5_MEASUREMENTS_DT_TYPE uint8_t
#define CAN_MSG_MCC19_5_MEASUREMENTS_DT_UNITS "%/255"


// MCC19_6 - Modulo controlador de carga
#define CAN_SIGNATURE_MCC19_6 239
// MCC19_6 - STATE - Module state report
#define CAN_MSG_MCC19_6_STATE_ID 108
#define CAN_MSG_MCC19_6_STATE_LENGTH 3
#define CAN_MSG_MCC19_6_STATE_FREQUENCY 1
#define CAN_MSG_MCC19_6_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_6_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_6_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_6_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MCC19_6_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MCC19_6_STATE_STATE_UNITS ""
#define CAN_MSG_MCC19_6_STATE_CONTROL_BYTE 2 //<!" Control flags for operating point
#define CAN_MSG_MCC19_6_STATE_CONTROL_TYPE uint8_t
#define CAN_MSG_MCC19_6_STATE_CONTROL_UNITS ""
#define CAN_MSG_MCC19_6_STATE_CONTROL_ENABLE_BIT 0
#define CAN_MSG_MCC19_6_STATE_CONTROL_VI_SAFE_RANGE_BIT 1
#define CAN_MSG_MCC19_6_STATE_CONTROL_VO_SAFE_RANGE_BIT 2
#define CAN_MSG_MCC19_6_STATE_CONTROL_VI_STABLE_BIT 3
#define CAN_MSG_MCC19_6_STATE_CONTROL_DT_SAFE_RANGE_BIT 4
// MCC19_6 - MEASUREMENTS - All measurements from the converter
#define CAN_MSG_MCC19_6_MEASUREMENTS_ID 207
#define CAN_MSG_MCC19_6_MEASUREMENTS_LENGTH 8
#define CAN_MSG_MCC19_6_MEASUREMENTS_FREQUENCY 30
#define CAN_MSG_MCC19_6_MEASUREMENTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCC19_6_MEASUREMENTS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCC19_6_MEASUREMENTS_SIGNATURE_UNITS ""
#define CAN_MSG_MCC19_6_MEASUREMENTS_OUTPUT_VOLTAGE_L_BYTE 1 //<!" Average output voltage, byte low
#define CAN_MSG_MCC19_6_MEASUREMENTS_OUTPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_6_MEASUREMENTS_OUTPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_6_MEASUREMENTS_OUTPUT_VOLTAGE_H_BYTE 2 //<!" Average output voltage, byte high
#define CAN_MSG_MCC19_6_MEASUREMENTS_OUTPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_6_MEASUREMENTS_OUTPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_CURRENT_L_BYTE 3 //<!" Average input current, byte low
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_CURRENT_L_TYPE uint16_t
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_CURRENT_L_UNITS "A/100"
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_CURRENT_H_BYTE 4 //<!" Average input current, byte high
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_CURRENT_H_TYPE uint16_t
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_CURRENT_H_UNITS "A/100"
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_VOLTAGE_L_BYTE 5 //<!" Average input voltage, byte low
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_VOLTAGE_H_BYTE 6 //<!" Average input voltage, byte high
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCC19_6_MEASUREMENTS_INPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCC19_6_MEASUREMENTS_DT_BYTE 7 //<!" converter's duty cycle
#define CAN_MSG_MCC19_6_MEASUREMENTS_DT_TYPE uint8_t
#define CAN_MSG_MCC19_6_MEASUREMENTS_DT_UNITS "%/255"


// MCB19_1 - Modulo de carregamento das baterias auxiliares
#define CAN_SIGNATURE_MCB19_1 220
// MCB19_1 - STATE - Module state report
#define CAN_MSG_MCB19_1_STATE_ID 109
#define CAN_MSG_MCB19_1_STATE_LENGTH 3
#define CAN_MSG_MCB19_1_STATE_FREQUENCY 1
#define CAN_MSG_MCB19_1_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCB19_1_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCB19_1_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MCB19_1_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MCB19_1_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MCB19_1_STATE_STATE_UNITS ""
#define CAN_MSG_MCB19_1_STATE_CONTROL_BYTE 2 //<!" Control flags for operating point
#define CAN_MSG_MCB19_1_STATE_CONTROL_TYPE uint8_t
#define CAN_MSG_MCB19_1_STATE_CONTROL_UNITS ""
#define CAN_MSG_MCB19_1_STATE_CONTROL_ENABLE_BIT 0
#define CAN_MSG_MCB19_1_STATE_CONTROL_VI_SAFE_RANGE_BIT 1
#define CAN_MSG_MCB19_1_STATE_CONTROL_VO_SAFE_RANGE_BIT 2
#define CAN_MSG_MCB19_1_STATE_CONTROL_VI_STABLE_BIT 3
#define CAN_MSG_MCB19_1_STATE_CONTROL_DT_SAFE_RANGE_BIT 4
// MCB19_1 - MEASUREMENTS - All measurements from the converter
#define CAN_MSG_MCB19_1_MEASUREMENTS_ID 208
#define CAN_MSG_MCB19_1_MEASUREMENTS_LENGTH 8
#define CAN_MSG_MCB19_1_MEASUREMENTS_FREQUENCY 10
#define CAN_MSG_MCB19_1_MEASUREMENTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCB19_1_MEASUREMENTS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCB19_1_MEASUREMENTS_SIGNATURE_UNITS ""
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_VOLTAGE_L_BYTE 1 //<!" Average output voltage, byte low
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_VOLTAGE_H_BYTE 2 //<!" Average output voltage, byte high
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_CURRENT_L_BYTE 3 //<!" Average output current, byte low
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_CURRENT_L_TYPE uint16_t
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_CURRENT_L_UNITS "A/100"
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_CURRENT_H_BYTE 4 //<!" Average output current, byte high
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_CURRENT_H_TYPE uint16_t
#define CAN_MSG_MCB19_1_MEASUREMENTS_OUTPUT_CURRENT_H_UNITS "A/100"
#define CAN_MSG_MCB19_1_MEASUREMENTS_INPUT_VOLTAGE_L_BYTE 5 //<!" Average input voltage, byte low
#define CAN_MSG_MCB19_1_MEASUREMENTS_INPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCB19_1_MEASUREMENTS_INPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCB19_1_MEASUREMENTS_INPUT_VOLTAGE_H_BYTE 6 //<!" Average input voltage, byte high
#define CAN_MSG_MCB19_1_MEASUREMENTS_INPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCB19_1_MEASUREMENTS_INPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCB19_1_MEASUREMENTS_DT_BYTE 7 //<!" converter's duty cycle
#define CAN_MSG_MCB19_1_MEASUREMENTS_DT_TYPE uint8_t
#define CAN_MSG_MCB19_1_MEASUREMENTS_DT_UNITS "%/255"


// MCB19_2 - Modulo de carregamento das baterias auxiliares
#define CAN_SIGNATURE_MCB19_2 221
// MCB19_2 - STATE - Module state report
#define CAN_MSG_MCB19_2_STATE_ID 110
#define CAN_MSG_MCB19_2_STATE_LENGTH 3
#define CAN_MSG_MCB19_2_STATE_FREQUENCY 1
#define CAN_MSG_MCB19_2_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCB19_2_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCB19_2_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MCB19_2_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MCB19_2_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MCB19_2_STATE_STATE_UNITS ""
#define CAN_MSG_MCB19_2_STATE_CONTROL_BYTE 2 //<!" Control flags for operating point
#define CAN_MSG_MCB19_2_STATE_CONTROL_TYPE uint8_t
#define CAN_MSG_MCB19_2_STATE_CONTROL_UNITS ""
#define CAN_MSG_MCB19_2_STATE_CONTROL_ENABLE_BIT 0
#define CAN_MSG_MCB19_2_STATE_CONTROL_VI_SAFE_RANGE_BIT 1
#define CAN_MSG_MCB19_2_STATE_CONTROL_VO_SAFE_RANGE_BIT 2
#define CAN_MSG_MCB19_2_STATE_CONTROL_VI_STABLE_BIT 3
#define CAN_MSG_MCB19_2_STATE_CONTROL_DT_SAFE_RANGE_BIT 4
// MCB19_2 - MEASUREMENTS - All measurements from the converter
#define CAN_MSG_MCB19_2_MEASUREMENTS_ID 209
#define CAN_MSG_MCB19_2_MEASUREMENTS_LENGTH 8
#define CAN_MSG_MCB19_2_MEASUREMENTS_FREQUENCY 10
#define CAN_MSG_MCB19_2_MEASUREMENTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCB19_2_MEASUREMENTS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCB19_2_MEASUREMENTS_SIGNATURE_UNITS ""
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_VOLTAGE_L_BYTE 1 //<!" Average output voltage, byte low
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_VOLTAGE_H_BYTE 2 //<!" Average output voltage, byte high
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_CURRENT_L_BYTE 3 //<!" Average output current, byte low
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_CURRENT_L_TYPE uint16_t
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_CURRENT_L_UNITS "A/100"
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_CURRENT_H_BYTE 4 //<!" Average output current, byte high
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_CURRENT_H_TYPE uint16_t
#define CAN_MSG_MCB19_2_MEASUREMENTS_OUTPUT_CURRENT_H_UNITS "A/100"
#define CAN_MSG_MCB19_2_MEASUREMENTS_INPUT_VOLTAGE_L_BYTE 5 //<!" Average input voltage, byte low
#define CAN_MSG_MCB19_2_MEASUREMENTS_INPUT_VOLTAGE_L_TYPE uint16_t
#define CAN_MSG_MCB19_2_MEASUREMENTS_INPUT_VOLTAGE_L_UNITS "V/100"
#define CAN_MSG_MCB19_2_MEASUREMENTS_INPUT_VOLTAGE_H_BYTE 6 //<!" Average input voltage, byte high
#define CAN_MSG_MCB19_2_MEASUREMENTS_INPUT_VOLTAGE_H_TYPE uint16_t
#define CAN_MSG_MCB19_2_MEASUREMENTS_INPUT_VOLTAGE_H_UNITS "V/100"
#define CAN_MSG_MCB19_2_MEASUREMENTS_DT_BYTE 7 //<!" converter's duty cycle
#define CAN_MSG_MCB19_2_MEASUREMENTS_DT_TYPE uint8_t
#define CAN_MSG_MCB19_2_MEASUREMENTS_DT_UNITS "%/255"


// MAC22 - Modulo de Acionamento da Contatora
#define CAN_SIGNATURE_MAC22 180
// MAC22 - STATE - Module state report
#define CAN_MSG_MAC22_STATE_ID 35
#define CAN_MSG_MAC22_STATE_LENGTH 3
#define CAN_MSG_MAC22_STATE_FREQUENCY 5
#define CAN_MSG_MAC22_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MAC22_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MAC22_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MAC22_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MAC22_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MAC22_STATE_STATE_UNITS ""
#define CAN_MSG_MAC22_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MAC22_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MAC22_STATE_ERROR_UNITS ""
// MAC22 - CONTACTOR - Contactor task response
#define CAN_MSG_MAC22_CONTACTOR_ID 34
#define CAN_MSG_MAC22_CONTACTOR_LENGTH 2
#define CAN_MSG_MAC22_CONTACTOR_FREQUENCY 50
#define CAN_MSG_MAC22_CONTACTOR_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MAC22_CONTACTOR_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MAC22_CONTACTOR_SIGNATURE_UNITS ""
#define CAN_MSG_MAC22_CONTACTOR_RESPONSE_BYTE 1 //<!" Contactor task response
#define CAN_MSG_MAC22_CONTACTOR_RESPONSE_TYPE uint8_t
#define CAN_MSG_MAC22_CONTACTOR_RESPONSE_UNITS ""


// MAM19 - Modulo de Acionamento do Motor
#define CAN_SIGNATURE_MAM19 190
// MAM19 - STATE - Module state report
#define CAN_MSG_MAM19_STATE_ID 99
#define CAN_MSG_MAM19_STATE_LENGTH 3
#define CAN_MSG_MAM19_STATE_FREQUENCY 5
#define CAN_MSG_MAM19_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MAM19_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MAM19_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MAM19_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MAM19_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MAM19_STATE_STATE_UNITS ""
#define CAN_MSG_MAM19_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MAM19_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MAM19_STATE_ERROR_UNITS ""
// MAM19 - MOTOR - Motor controller parameters
#define CAN_MSG_MAM19_MOTOR_ID 98
#define CAN_MSG_MAM19_MOTOR_LENGTH 3
#define CAN_MSG_MAM19_MOTOR_FREQUENCY 50
#define CAN_MSG_MAM19_MOTOR_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MAM19_MOTOR_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MAM19_MOTOR_SIGNATURE_UNITS ""
#define CAN_MSG_MAM19_MOTOR_D_BYTE 1 //<!" Motor Duty Cycle
#define CAN_MSG_MAM19_MOTOR_D_TYPE uint8_t
#define CAN_MSG_MAM19_MOTOR_D_UNITS "%"
#define CAN_MSG_MAM19_MOTOR_I_BYTE 2 //<!" Motor Soft Start
#define CAN_MSG_MAM19_MOTOR_I_TYPE uint8_t
#define CAN_MSG_MAM19_MOTOR_I_UNITS "%"
// MAM19 - CONTACTOR - Contactor requests
#define CAN_MSG_MAM19_CONTACTOR_ID 36
#define CAN_MSG_MAM19_CONTACTOR_LENGTH 2
#define CAN_MSG_MAM19_CONTACTOR_FREQUENCY 5
#define CAN_MSG_MAM19_CONTACTOR_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MAM19_CONTACTOR_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MAM19_CONTACTOR_SIGNATURE_UNITS ""
#define CAN_MSG_MAM19_CONTACTOR_REQUEST_BYTE 1 //<!" Control the Contactor State
#define CAN_MSG_MAM19_CONTACTOR_REQUEST_TYPE uint8_t
#define CAN_MSG_MAM19_CONTACTOR_REQUEST_UNITS ""


// MAB19 - Modulo de Acionamento das Bombas de Porao
#define CAN_SIGNATURE_MAB19 230
// MAB19 - STATE - Module state report
#define CAN_MSG_MAB19_STATE_ID 111
#define CAN_MSG_MAB19_STATE_LENGTH 3
#define CAN_MSG_MAB19_STATE_FREQUENCY 0
#define CAN_MSG_MAB19_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MAB19_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MAB19_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MAB19_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MAB19_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MAB19_STATE_STATE_UNITS ""
#define CAN_MSG_MAB19_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MAB19_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MAB19_STATE_ERROR_UNITS ""
// MAB19 - PUMPS - Pumps state
#define CAN_MSG_MAB19_PUMPS_ID 210
#define CAN_MSG_MAB19_PUMPS_LENGTH 2
#define CAN_MSG_MAB19_PUMPS_FREQUENCY 0
#define CAN_MSG_MAB19_PUMPS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MAB19_PUMPS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MAB19_PUMPS_SIGNATURE_UNITS ""
#define CAN_MSG_MAB19_PUMPS_PUMPS_BYTE 1 //<!" Pumps state
#define CAN_MSG_MAB19_PUMPS_PUMPS_TYPE uint8_t
#define CAN_MSG_MAB19_PUMPS_PUMPS_UNITS ""
#define CAN_MSG_MAB19_PUMPS_PUMPS_PUMP1_BIT 0
#define CAN_MSG_MAB19_PUMPS_PUMPS_PUMP2_BIT 1
#define CAN_MSG_MAB19_PUMPS_PUMPS_PUMP3_BIT 2


// MSC19_1 - Main Battery Voltage Sensor
#define CAN_SIGNATURE_MSC19_1 250
// MSC19_1 - STATE - Module state report
#define CAN_MSG_MSC19_1_STATE_ID 112
#define CAN_MSG_MSC19_1_STATE_LENGTH 3
#define CAN_MSG_MSC19_1_STATE_FREQUENCY 1
#define CAN_MSG_MSC19_1_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSC19_1_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSC19_1_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MSC19_1_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MSC19_1_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MSC19_1_STATE_STATE_UNITS ""
#define CAN_MSG_MSC19_1_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MSC19_1_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MSC19_1_STATE_ERROR_UNITS ""
// MSC19_1 - ADC - Voltage measurements
#define CAN_MSG_MSC19_1_ADC_ID 211
#define CAN_MSG_MSC19_1_ADC_LENGTH 7
#define CAN_MSG_MSC19_1_ADC_FREQUENCY 10
#define CAN_MSG_MSC19_1_ADC_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSC19_1_ADC_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSC19_1_ADC_SIGNATURE_UNITS ""
#define CAN_MSG_MSC19_1_ADC_AVG_L_BYTE 1 //<!" Average, byte low
#define CAN_MSG_MSC19_1_ADC_AVG_L_TYPE uint16_t
#define CAN_MSG_MSC19_1_ADC_AVG_L_UNITS "V/100"
#define CAN_MSG_MSC19_1_ADC_AVG_H_BYTE 2 //<!" Average, byte high
#define CAN_MSG_MSC19_1_ADC_AVG_H_TYPE uint16_t
#define CAN_MSG_MSC19_1_ADC_AVG_H_UNITS "V/100"
#define CAN_MSG_MSC19_1_ADC_MIN_L_BYTE 3 //<!" Min byte low
#define CAN_MSG_MSC19_1_ADC_MIN_L_TYPE uint16_t
#define CAN_MSG_MSC19_1_ADC_MIN_L_UNITS "V/100"
#define CAN_MSG_MSC19_1_ADC_MIN_H_BYTE 4 //<!" Min byte high
#define CAN_MSG_MSC19_1_ADC_MIN_H_TYPE uint16_t
#define CAN_MSG_MSC19_1_ADC_MIN_H_UNITS "V/100"
#define CAN_MSG_MSC19_1_ADC_MAX_L_BYTE 5 //<!" Max byte low
#define CAN_MSG_MSC19_1_ADC_MAX_L_TYPE uint16_t
#define CAN_MSG_MSC19_1_ADC_MAX_L_UNITS "V/100"
#define CAN_MSG_MSC19_1_ADC_MAX_H_BYTE 6 //<!" Max byte low
#define CAN_MSG_MSC19_1_ADC_MAX_H_TYPE uint16_t
#define CAN_MSG_MSC19_1_ADC_MAX_H_UNITS "V/100"


// MSC19_2 - Auxilliary Battery Voltage Sensor
#define CAN_SIGNATURE_MSC19_2 251
// MSC19_2 - STATE - Module state report
#define CAN_MSG_MSC19_2_STATE_ID 113
#define CAN_MSG_MSC19_2_STATE_LENGTH 3
#define CAN_MSG_MSC19_2_STATE_FREQUENCY 1
#define CAN_MSG_MSC19_2_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSC19_2_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSC19_2_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MSC19_2_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MSC19_2_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MSC19_2_STATE_STATE_UNITS ""
#define CAN_MSG_MSC19_2_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MSC19_2_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MSC19_2_STATE_ERROR_UNITS ""
// MSC19_2 - ADC - Voltage measurements
#define CAN_MSG_MSC19_2_ADC_ID 212
#define CAN_MSG_MSC19_2_ADC_LENGTH 7
#define CAN_MSG_MSC19_2_ADC_FREQUENCY 10
#define CAN_MSG_MSC19_2_ADC_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSC19_2_ADC_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSC19_2_ADC_SIGNATURE_UNITS ""
#define CAN_MSG_MSC19_2_ADC_AVG_L_BYTE 1 //<!" Average, byte low
#define CAN_MSG_MSC19_2_ADC_AVG_L_TYPE uint16_t
#define CAN_MSG_MSC19_2_ADC_AVG_L_UNITS "V/100"
#define CAN_MSG_MSC19_2_ADC_AVG_H_BYTE 2 //<!" Average, byte high
#define CAN_MSG_MSC19_2_ADC_AVG_H_TYPE uint16_t
#define CAN_MSG_MSC19_2_ADC_AVG_H_UNITS "V/100"
#define CAN_MSG_MSC19_2_ADC_MIN_L_BYTE 3 //<!" Min byte low
#define CAN_MSG_MSC19_2_ADC_MIN_L_TYPE uint16_t
#define CAN_MSG_MSC19_2_ADC_MIN_L_UNITS "V/100"
#define CAN_MSG_MSC19_2_ADC_MIN_H_BYTE 4 //<!" Min byte high
#define CAN_MSG_MSC19_2_ADC_MIN_H_TYPE uint16_t
#define CAN_MSG_MSC19_2_ADC_MIN_H_UNITS "V/100"
#define CAN_MSG_MSC19_2_ADC_MAX_L_BYTE 5 //<!" Max byte low
#define CAN_MSG_MSC19_2_ADC_MAX_L_TYPE uint16_t
#define CAN_MSG_MSC19_2_ADC_MAX_L_UNITS "V/100"
#define CAN_MSG_MSC19_2_ADC_MAX_H_BYTE 6 //<!" Max byte low
#define CAN_MSG_MSC19_2_ADC_MAX_H_TYPE uint16_t
#define CAN_MSG_MSC19_2_ADC_MAX_H_UNITS "V/100"


// MSC19_3 - Extra Battery Voltage Sensor
#define CAN_SIGNATURE_MSC19_3 252
// MSC19_3 - STATE - Module state report
#define CAN_MSG_MSC19_3_STATE_ID 114
#define CAN_MSG_MSC19_3_STATE_LENGTH 3
#define CAN_MSG_MSC19_3_STATE_FREQUENCY 1
#define CAN_MSG_MSC19_3_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSC19_3_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSC19_3_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MSC19_3_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MSC19_3_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MSC19_3_STATE_STATE_UNITS ""
#define CAN_MSG_MSC19_3_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MSC19_3_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MSC19_3_STATE_ERROR_UNITS ""
// MSC19_3 - ADC - Voltage measurements
#define CAN_MSG_MSC19_3_ADC_ID 213
#define CAN_MSG_MSC19_3_ADC_LENGTH 7
#define CAN_MSG_MSC19_3_ADC_FREQUENCY 10
#define CAN_MSG_MSC19_3_ADC_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSC19_3_ADC_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSC19_3_ADC_SIGNATURE_UNITS ""
#define CAN_MSG_MSC19_3_ADC_AVG_L_BYTE 1 //<!" Average, byte low
#define CAN_MSG_MSC19_3_ADC_AVG_L_TYPE uint16_t
#define CAN_MSG_MSC19_3_ADC_AVG_L_UNITS "V/100"
#define CAN_MSG_MSC19_3_ADC_AVG_H_BYTE 2 //<!" Average, byte high
#define CAN_MSG_MSC19_3_ADC_AVG_H_TYPE uint16_t
#define CAN_MSG_MSC19_3_ADC_AVG_H_UNITS "V/100"
#define CAN_MSG_MSC19_3_ADC_MIN_L_BYTE 3 //<!" Min byte low
#define CAN_MSG_MSC19_3_ADC_MIN_L_TYPE uint16_t
#define CAN_MSG_MSC19_3_ADC_MIN_L_UNITS "V/100"
#define CAN_MSG_MSC19_3_ADC_MIN_H_BYTE 4 //<!" Min byte high
#define CAN_MSG_MSC19_3_ADC_MIN_H_TYPE uint16_t
#define CAN_MSG_MSC19_3_ADC_MIN_H_UNITS "V/100"
#define CAN_MSG_MSC19_3_ADC_MAX_L_BYTE 5 //<!" Max byte low
#define CAN_MSG_MSC19_3_ADC_MAX_L_TYPE uint16_t
#define CAN_MSG_MSC19_3_ADC_MAX_L_UNITS "V/100"
#define CAN_MSG_MSC19_3_ADC_MAX_H_BYTE 6 //<!" Max byte low
#define CAN_MSG_MSC19_3_ADC_MAX_H_TYPE uint16_t
#define CAN_MSG_MSC19_3_ADC_MAX_H_UNITS "V/100"


// MSC19_4 - Main Battery Input Current Sensor
#define CAN_SIGNATURE_MSC19_4 253
// MSC19_4 - STATE - Module state report
#define CAN_MSG_MSC19_4_STATE_ID 115
#define CAN_MSG_MSC19_4_STATE_LENGTH 3
#define CAN_MSG_MSC19_4_STATE_FREQUENCY 1
#define CAN_MSG_MSC19_4_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSC19_4_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSC19_4_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MSC19_4_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MSC19_4_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MSC19_4_STATE_STATE_UNITS ""
#define CAN_MSG_MSC19_4_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MSC19_4_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MSC19_4_STATE_ERROR_UNITS ""
// MSC19_4 - ADC - Current measurements
#define CAN_MSG_MSC19_4_ADC_ID 214
#define CAN_MSG_MSC19_4_ADC_LENGTH 7
#define CAN_MSG_MSC19_4_ADC_FREQUENCY 10
#define CAN_MSG_MSC19_4_ADC_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSC19_4_ADC_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSC19_4_ADC_SIGNATURE_UNITS ""
#define CAN_MSG_MSC19_4_ADC_AVG_L_BYTE 1 //<!" Average, byte low
#define CAN_MSG_MSC19_4_ADC_AVG_L_TYPE uint16_t
#define CAN_MSG_MSC19_4_ADC_AVG_L_UNITS "A/100"
#define CAN_MSG_MSC19_4_ADC_AVG_H_BYTE 2 //<!" Average, byte high
#define CAN_MSG_MSC19_4_ADC_AVG_H_TYPE uint16_t
#define CAN_MSG_MSC19_4_ADC_AVG_H_UNITS "A/100"
#define CAN_MSG_MSC19_4_ADC_MIN_L_BYTE 3 //<!" Min byte low
#define CAN_MSG_MSC19_4_ADC_MIN_L_TYPE uint16_t
#define CAN_MSG_MSC19_4_ADC_MIN_L_UNITS "A/100"
#define CAN_MSG_MSC19_4_ADC_MIN_H_BYTE 4 //<!" Min byte high
#define CAN_MSG_MSC19_4_ADC_MIN_H_TYPE uint16_t
#define CAN_MSG_MSC19_4_ADC_MIN_H_UNITS "A/100"
#define CAN_MSG_MSC19_4_ADC_MAX_L_BYTE 5 //<!" Max byte low
#define CAN_MSG_MSC19_4_ADC_MAX_L_TYPE uint16_t
#define CAN_MSG_MSC19_4_ADC_MAX_L_UNITS "A/100"
#define CAN_MSG_MSC19_4_ADC_MAX_H_BYTE 6 //<!" Max byte low
#define CAN_MSG_MSC19_4_ADC_MAX_H_TYPE uint16_t
#define CAN_MSG_MSC19_4_ADC_MAX_H_UNITS "A/100"


// MSC19_5 - Main Battery Output Current Sensor
#define CAN_SIGNATURE_MSC19_5 254
// MSC19_5 - STATE - Module state report
#define CAN_MSG_MSC19_5_STATE_ID 116
#define CAN_MSG_MSC19_5_STATE_LENGTH 3
#define CAN_MSG_MSC19_5_STATE_FREQUENCY 1
#define CAN_MSG_MSC19_5_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSC19_5_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSC19_5_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MSC19_5_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MSC19_5_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MSC19_5_STATE_STATE_UNITS ""
#define CAN_MSG_MSC19_5_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MSC19_5_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MSC19_5_STATE_ERROR_UNITS ""
// MSC19_5 - ADC - Current measurements
#define CAN_MSG_MSC19_5_ADC_ID 215
#define CAN_MSG_MSC19_5_ADC_LENGTH 7
#define CAN_MSG_MSC19_5_ADC_FREQUENCY 10
#define CAN_MSG_MSC19_5_ADC_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSC19_5_ADC_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSC19_5_ADC_SIGNATURE_UNITS ""
#define CAN_MSG_MSC19_5_ADC_AVG_L_BYTE 1 //<!" Average, byte low
#define CAN_MSG_MSC19_5_ADC_AVG_L_TYPE uint16_t
#define CAN_MSG_MSC19_5_ADC_AVG_L_UNITS "A/100"
#define CAN_MSG_MSC19_5_ADC_AVG_H_BYTE 2 //<!" Average, byte high
#define CAN_MSG_MSC19_5_ADC_AVG_H_TYPE uint16_t
#define CAN_MSG_MSC19_5_ADC_AVG_H_UNITS "A/100"
#define CAN_MSG_MSC19_5_ADC_MIN_L_BYTE 3 //<!" Min byte low
#define CAN_MSG_MSC19_5_ADC_MIN_L_TYPE uint16_t
#define CAN_MSG_MSC19_5_ADC_MIN_L_UNITS "A/100"
#define CAN_MSG_MSC19_5_ADC_MIN_H_BYTE 4 //<!" Min byte high
#define CAN_MSG_MSC19_5_ADC_MIN_H_TYPE uint16_t
#define CAN_MSG_MSC19_5_ADC_MIN_H_UNITS "A/100"
#define CAN_MSG_MSC19_5_ADC_MAX_L_BYTE 5 //<!" Max byte low
#define CAN_MSG_MSC19_5_ADC_MAX_L_TYPE uint16_t
#define CAN_MSG_MSC19_5_ADC_MAX_L_UNITS "A/100"
#define CAN_MSG_MSC19_5_ADC_MAX_H_BYTE 6 //<!" Max byte low
#define CAN_MSG_MSC19_5_ADC_MAX_H_TYPE uint16_t
#define CAN_MSG_MSC19_5_ADC_MAX_H_UNITS "A/100"


// MCS19 - Modulo de Carregamento do Sistema
#define CAN_SIGNATURE_MCS19 200
// MCS19 - STATE - Module state report
#define CAN_MSG_MCS19_STATE_ID 117
#define CAN_MSG_MCS19_STATE_LENGTH 3
#define CAN_MSG_MCS19_STATE_FREQUENCY 1
#define CAN_MSG_MCS19_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCS19_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCS19_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MCS19_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MCS19_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MCS19_STATE_STATE_UNITS ""
#define CAN_MSG_MCS19_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MCS19_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MCS19_STATE_ERROR_UNITS ""
// MCS19 - START_STAGES - Boat charging // Boat on
#define CAN_MSG_MCS19_START_STAGES_ID 37
#define CAN_MSG_MCS19_START_STAGES_LENGTH 3
#define CAN_MSG_MCS19_START_STAGES_FREQUENCY 50
#define CAN_MSG_MCS19_START_STAGES_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCS19_START_STAGES_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCS19_START_STAGES_SIGNATURE_UNITS ""
#define CAN_MSG_MCS19_START_STAGES_MAIN_RELAY_BYTE 1 //<!" Boat on/off
#define CAN_MSG_MCS19_START_STAGES_MAIN_RELAY_TYPE uint8_t
#define CAN_MSG_MCS19_START_STAGES_MAIN_RELAY_UNITS ""
#define CAN_MSG_MCS19_START_STAGES_MAIN_RELAY_MAIN_RELAY_BIT 0
#define CAN_MSG_MCS19_START_STAGES_CHARGE_RELAY_BYTE 2 //<!" Boat Charging
#define CAN_MSG_MCS19_START_STAGES_CHARGE_RELAY_TYPE uint8_t
#define CAN_MSG_MCS19_START_STAGES_CHARGE_RELAY_UNITS ""
#define CAN_MSG_MCS19_START_STAGES_CHARGE_RELAY_CHARGE_RELAY_BIT 0
// MCS19 - BAT - battery voltage values
#define CAN_MSG_MCS19_BAT_ID 216
#define CAN_MSG_MCS19_BAT_LENGTH 7
#define CAN_MSG_MCS19_BAT_FREQUENCY 10
#define CAN_MSG_MCS19_BAT_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCS19_BAT_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCS19_BAT_SIGNATURE_UNITS ""
#define CAN_MSG_MCS19_BAT_AVG_L_BYTE 1 //<!" Average, byte low
#define CAN_MSG_MCS19_BAT_AVG_L_TYPE uint16_t
#define CAN_MSG_MCS19_BAT_AVG_L_UNITS ""
#define CAN_MSG_MCS19_BAT_AVG_H_BYTE 2 //<!" Average, byte high
#define CAN_MSG_MCS19_BAT_AVG_H_TYPE uint16_t
#define CAN_MSG_MCS19_BAT_AVG_H_UNITS ""
#define CAN_MSG_MCS19_BAT_MIN_L_BYTE 3 //<!" Min byte low
#define CAN_MSG_MCS19_BAT_MIN_L_TYPE uint16_t
#define CAN_MSG_MCS19_BAT_MIN_L_UNITS ""
#define CAN_MSG_MCS19_BAT_MIN_H_BYTE 4 //<!" Min byte high
#define CAN_MSG_MCS19_BAT_MIN_H_TYPE uint16_t
#define CAN_MSG_MCS19_BAT_MIN_H_UNITS ""
#define CAN_MSG_MCS19_BAT_MAX_L_BYTE 5 //<!" Max byte low
#define CAN_MSG_MCS19_BAT_MAX_L_TYPE uint16_t
#define CAN_MSG_MCS19_BAT_MAX_L_UNITS ""
#define CAN_MSG_MCS19_BAT_MAX_H_BYTE 6 //<!" Max byte low
#define CAN_MSG_MCS19_BAT_MAX_H_TYPE uint16_t
#define CAN_MSG_MCS19_BAT_MAX_H_UNITS ""
// MCS19 - CAP - capacitor bank voltage values
#define CAN_MSG_MCS19_CAP_ID 217
#define CAN_MSG_MCS19_CAP_LENGTH 7
#define CAN_MSG_MCS19_CAP_FREQUENCY 10
#define CAN_MSG_MCS19_CAP_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MCS19_CAP_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MCS19_CAP_SIGNATURE_UNITS ""
#define CAN_MSG_MCS19_CAP_AVG_L_BYTE 1 //<!" Average, byte low
#define CAN_MSG_MCS19_CAP_AVG_L_TYPE uint16_t
#define CAN_MSG_MCS19_CAP_AVG_L_UNITS ""
#define CAN_MSG_MCS19_CAP_AVG_H_BYTE 2 //<!" Average, byte high
#define CAN_MSG_MCS19_CAP_AVG_H_TYPE uint16_t
#define CAN_MSG_MCS19_CAP_AVG_H_UNITS ""
#define CAN_MSG_MCS19_CAP_MIN_L_BYTE 3 //<!" Min byte low
#define CAN_MSG_MCS19_CAP_MIN_L_TYPE uint16_t
#define CAN_MSG_MCS19_CAP_MIN_L_UNITS ""
#define CAN_MSG_MCS19_CAP_MIN_H_BYTE 4 //<!" Min byte high
#define CAN_MSG_MCS19_CAP_MIN_H_TYPE uint16_t
#define CAN_MSG_MCS19_CAP_MIN_H_UNITS ""
#define CAN_MSG_MCS19_CAP_MAX_L_BYTE 5 //<!" Max byte low
#define CAN_MSG_MCS19_CAP_MAX_L_TYPE uint16_t
#define CAN_MSG_MCS19_CAP_MAX_L_UNITS ""
#define CAN_MSG_MCS19_CAP_MAX_H_BYTE 6 //<!" Max byte low
#define CAN_MSG_MCS19_CAP_MAX_H_TYPE uint16_t
#define CAN_MSG_MCS19_CAP_MAX_H_UNITS ""


// MT19 - Modulo Tacometro
#define CAN_SIGNATURE_MT19 255
// MT19 - STATE - Module state report
#define CAN_MSG_MT19_STATE_ID 218
#define CAN_MSG_MT19_STATE_LENGTH 3
#define CAN_MSG_MT19_STATE_FREQUENCY 0
#define CAN_MSG_MT19_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MT19_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MT19_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MT19_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MT19_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MT19_STATE_STATE_UNITS ""
#define CAN_MSG_MT19_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MT19_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MT19_STATE_ERROR_UNITS ""
// MT19 - RPM - RPM motor values
#define CAN_MSG_MT19_RPM_ID 219
#define CAN_MSG_MT19_RPM_LENGTH 3
#define CAN_MSG_MT19_RPM_FREQUENCY 0
#define CAN_MSG_MT19_RPM_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MT19_RPM_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MT19_RPM_SIGNATURE_UNITS ""
#define CAN_MSG_MT19_RPM_AVG_L_BYTE 1 //<!" RPM Average, byte low
#define CAN_MSG_MT19_RPM_AVG_L_TYPE uint16_t
#define CAN_MSG_MT19_RPM_AVG_L_UNITS ""
#define CAN_MSG_MT19_RPM_AVG_H_BYTE 2 //<!" RPM Average, byte high
#define CAN_MSG_MT19_RPM_AVG_H_TYPE uint16_t
#define CAN_MSG_MT19_RPM_AVG_H_UNITS ""


// MSWI19 - Modulo de Interface de Controle
#define CAN_SIGNATURE_MSWI19 241
// MSWI19 - STATE - Module state report
#define CAN_MSG_MSWI19_STATE_ID 9
#define CAN_MSG_MSWI19_STATE_LENGTH 3
#define CAN_MSG_MSWI19_STATE_FREQUENCY 5
#define CAN_MSG_MSWI19_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSWI19_STATE_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSWI19_STATE_SIGNATURE_UNITS ""
#define CAN_MSG_MSWI19_STATE_STATE_BYTE 1 //<!" State code
#define CAN_MSG_MSWI19_STATE_STATE_TYPE uint8_t
#define CAN_MSG_MSWI19_STATE_STATE_UNITS ""
#define CAN_MSG_MSWI19_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_MSG_MSWI19_STATE_ERROR_TYPE uint8_t
#define CAN_MSG_MSWI19_STATE_ERROR_UNITS ""
// MSWI19 - MOTOR - Motor controller parameters
#define CAN_MSG_MSWI19_MOTOR_ID 10
#define CAN_MSG_MSWI19_MOTOR_LENGTH 4
#define CAN_MSG_MSWI19_MOTOR_FREQUENCY 50
#define CAN_MSG_MSWI19_MOTOR_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSWI19_MOTOR_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSWI19_MOTOR_SIGNATURE_UNITS ""
#define CAN_MSG_MSWI19_MOTOR_MOTOR_BYTE 1 //<!" Motor state
#define CAN_MSG_MSWI19_MOTOR_MOTOR_TYPE uint8_t
#define CAN_MSG_MSWI19_MOTOR_MOTOR_UNITS ""
#define CAN_MSG_MSWI19_MOTOR_MOTOR_MOTOR_ON_BIT 0
#define CAN_MSG_MSWI19_MOTOR_MOTOR_DMS_ON_BIT 1
#define CAN_MSG_MSWI19_MOTOR_D_BYTE 2 //<!" Motor Duty Cycle
#define CAN_MSG_MSWI19_MOTOR_D_TYPE uint8_t
#define CAN_MSG_MSWI19_MOTOR_D_UNITS "%"
#define CAN_MSG_MSWI19_MOTOR_I_BYTE 3 //<!" Motor Soft Start
#define CAN_MSG_MSWI19_MOTOR_I_TYPE uint8_t
#define CAN_MSG_MSWI19_MOTOR_I_UNITS "%"
// MSWI19 - PUMPS - Pumps controller parameters
#define CAN_MSG_MSWI19_PUMPS_ID 220
#define CAN_MSG_MSWI19_PUMPS_LENGTH 2
#define CAN_MSG_MSWI19_PUMPS_FREQUENCY 0
#define CAN_MSG_MSWI19_PUMPS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSWI19_PUMPS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSWI19_PUMPS_SIGNATURE_UNITS ""
#define CAN_MSG_MSWI19_PUMPS_PUMPS_BYTE 1 //<!" Pumps state
#define CAN_MSG_MSWI19_PUMPS_PUMPS_TYPE uint8_t
#define CAN_MSG_MSWI19_PUMPS_PUMPS_UNITS ""
#define CAN_MSG_MSWI19_PUMPS_PUMPS_PUMP1_BIT 0
#define CAN_MSG_MSWI19_PUMPS_PUMPS_PUMP2_BIT 1
#define CAN_MSG_MSWI19_PUMPS_PUMPS_PUMP3_BIT 2
// MSWI19 - MPPTS - Mppts controller parameters
#define CAN_MSG_MSWI19_MPPTS_ID 221
#define CAN_MSG_MSWI19_MPPTS_LENGTH 3
#define CAN_MSG_MSWI19_MPPTS_FREQUENCY 0
#define CAN_MSG_MSWI19_MPPTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSWI19_MPPTS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSWI19_MPPTS_SIGNATURE_UNITS ""
#define CAN_MSG_MSWI19_MPPTS_MPPTS_ON_BYTE 1 //<!" MPPTs state
#define CAN_MSG_MSWI19_MPPTS_MPPTS_ON_TYPE uint8_t
#define CAN_MSG_MSWI19_MPPTS_MPPTS_ON_UNITS ""
#define CAN_MSG_MSWI19_MPPTS_MPPTS_ON_MPPTS_ON_BIT 0
#define CAN_MSG_MSWI19_MPPTS_POT_BYTE 2 //<!" MPPTs maximum power limitation
#define CAN_MSG_MSWI19_MPPTS_POT_TYPE uint8_t
#define CAN_MSG_MSWI19_MPPTS_POT_UNITS "%"
// MSWI19 - MCS - MCS controller parameters
#define CAN_MSG_MSWI19_MCS_ID 40
#define CAN_MSG_MSWI19_MCS_LENGTH 2
#define CAN_MSG_MSWI19_MCS_FREQUENCY 1
#define CAN_MSG_MSWI19_MCS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MSWI19_MCS_SIGNATURE_TYPE uint8_t
#define CAN_MSG_MSWI19_MCS_SIGNATURE_UNITS ""
#define CAN_MSG_MSWI19_MCS_BOAT_ON_BYTE 1 //<!" Boat state
#define CAN_MSG_MSWI19_MCS_BOAT_ON_TYPE uint8_t
#define CAN_MSG_MSWI19_MCS_BOAT_ON_UNITS ""
#define CAN_MSG_MSWI19_MCS_BOAT_ON_BOAT_ON_BIT 0


